apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup
spec:
  schdule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job
              image: busybox
              command: ["sh","-c","echo running"]
          restartPolicy: OnFailure
